### ISSUE TITLE
do not reuse existing configuration on connect

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#351] opened 2021-12-30 21:50 UTC
It seems the Android client uses the configuration it already has when connecting to the server. This is not allowed with APIv3. It results in AUTH_FAILED which the client displays as:

> Unable to connect
> An unexpected error occurred while connecting to this VPN provider: null

**Comment by fantostisch** [comment] 2022-01-03 21:57
This was caused by a bug which allowed the user to switch profiles when the VPN is connected when using V3 API after disconnecting and connecting. When then disconnecting, it attempts to remove the configuration of the wrong profile which results in the configuration of the existing profile to be reused next time. Fixed in https://github.com/fantostisch/android/commit/6f0a6c9ce1e6b794480cebe1f52fa62185f73f32

**Comment by fantostisch** [comment] 2022-01-03 22:45
Issue is not completely fixed yet, seems like the same issue occurs when quickly and repeatedly connecting and disconnecting.

**Comment by fantostisch** [comment] 2022-01-04 21:06
Fixed in https://github.com/eduvpn/android/pull/349/commits/e9b666591ed20ab9bac9e1391dfbfd152c928975, was caused by the disconnect call of a previous disconnect happening after a connect call. This could happen if the user disconnects when the VPN was currently connecting and then immediately connects.

**Closed** 2022-04-22 11:37 UTC
Labels: bug, API_v3
