### ISSUE TITLE
User gets redirected to 'New config' page from app

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#48] opened 2016-11-03 12:27 UTC
@dzolnai @fkooman I don't know if this is a problem in the app or on the server, but you can figure that out together :).

There are multiple cases of people that are testing the app but get redirected to the wrong page. When they use the Development-instance (labrat.eduvpn.nl) they should login with SURFconext and then see the oauth approval screen. When they select 'Approve' they return to the app and can connnect to the configured profiles. 

This actually does not work: people get redirected to the 'New Config' page instead of the oauth approval page. This is really confusing for them since they will download a file without knowing what to do next.

Any idea what can be wrong?

**Comment by dzolnai** [comment] 2016-11-03 12:44
> This actually does not work: people get redirected to the 'New Config' page instead of the oauth approval page. This is really confusing for them since they will download a file without knowing what to do next.

Can you describe these pages? There is no new config page in the app, so this happens in the browser? Does this mean that the browser does not open the app, but redirects to another page?

> oauth approval page

What is this page?

Maybe some screenshots can help clarify the issue.

**Comment by sveeke** [comment] 2016-11-03 13:03
> Can you describe these pages? There is no new config page in the app, so this happens in the browser? Does this mean that the browser does not open the app, but redirects to another page?
It indeed happens in the browser, not in the app. It looks like the browser does not open the oauth-page but instead forwards the user to the create config page on the user-portal.

> What is this page?
With my limited knowlegde on this: when the token is being sent back to the user, oauth wants to make sure that the user approves. It does this by showing a screen where the user can approve or cancel the tokenexchange. 

>Maybe some screenshots can help clarify the issue.
![screenshot_20161103-135828](https://cloud.githubusercontent.com/assets/12334213/19966900/275eb6a2-a1ce-11e6-9289-329c5b2cb3fe.png)

The new-config screen I am talking about is this screen: https://labrat.eduvpn.nl/portal/new

**Comment by dzolnai** [comment] 2016-11-03 13:05
Ok, seems like a server issue to me. Assigning @fkooman.

**Comment by fkooman** [comment] 2016-11-07 19:10
@sveeke: which version of the app? the one on http://145.100.180.98/app-debug.apk? For me it works fine with labrat...

**Comment by sveeke** [comment] 2016-11-07 19:20
I had it only one time with an older version of the app, but two testers @ UT, student @ SURFnet and Rogier all had this problem with the latest version of the app. I already tried to reproduce it, but on my phone it seems to be working okay.

**Comment by fkooman** [comment] 2016-11-07 19:26
I am not sure what it could be then, and I am not sure how we can actually check that they run the latest version?

**Comment by fkooman** [comment] 2016-11-07 19:31
I uploaded the latest version now here: http://eduvpn.surfcloud.nl/eduvpn-20161027.apk

**Comment by dzolnai** [comment] 2016-11-08 08:58
It is also possible that Firefox does not open the app from the URL.
I tested it with the latest stable version and it seems to work for me correctly though.

**Comment by sveeke** [comment] 2016-11-08 18:08
I encountered this bug only one time (a lot of app versions back) and that was on Chrome for Android. I can ask tomorrow which browser was used by the colleague that had this issue, maybe that helps a bit.

**Comment by sveeke** [comment] 2016-11-10 13:26
To add some more information: we think the bug only shows itself the first time a user installs and uses the eduVPN-app. Until now it is not reproducable after the first time the bug has occured, but when you flash the device it happens again.

**Comment by efef** [comment] 2016-11-10 15:46
I installed eduvpn-20161109_01.apk on mij Nexus 7 2013 tablet in order to re-enact this issue. The way how I could re-enact is like this:
-do the usual stuff, login via onegini (I always use a onegini local account and not social login), make sure the eduVPN is green and connected then
-disconnect wifi (so there is NO internet)
-click disconnect
-you'll see an Exclamation mark because the 'profiles' couldn't be loaded, turn WiFi ON again
-optional step: close your browser in order to remove session cookies
-click on the Exclamation mark, choose 'log in'
-choose identity provider Onegini and after filling-in name/password you'll get the webpage “your connected companies" (see screenshot)
-when choosing 'back' in browser and forward again to onegini login I once got the "new" configuration webpage of eduVPN in chrome instead of returning back to the eduvpn app

![screenshot_2016-11-10-12-31-39](https://cloud.githubusercontent.com/assets/3393474/20183313/29b35be6-a765-11e6-8818-3ee4f8baaaf1.png)

**Comment by dzolnai** [comment] 2016-11-10 18:31
Thank you for the reproduction steps, although it still works for me, even after deleting all Chrome data.
From what I can see, this boils to down to something cookie related, where Onegini redirects to a different page if this is the first visit of the user maybe?
Anyways, it seems this is a problem in the site itself instead of the app.

**Comment by fkooman** [comment] 2016-11-10 18:37
I was also unable to reproduce it using the Nexus 7 2013 all updates + factory reset.

**Comment by fkooman** [comment] 2016-11-17 10:03
I also got this Onegini issue at some point on iOS, just trying to login to the user portal, instead of redirecting back I went to the "companies" page. Maybe I clicked wrong, or maybe something is up with (certain) browsers and Onegini?

**Comment by fkooman** [comment] 2016-12-13 14:02
this is fixed now, the problem was related to obtaining an OAuth token for VOOT (group membership) on first login which triggered a redirect to the "/new" page. It only happened once.

**Closed by fkooman** 2016-12-13 14:02 UTC
Labels: bug, not an app bug
