### ISSUE TITLE
"eduVPN is gestopt"

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/android#98] opened 2017-09-05 08:32 UTC
After setting up a connection and i go to connection info > view log > press the cross in the right corner i have 3 options i can choose:

Opnieuw verbinden
annuleren
verbinding verbreken

(btw, not all options can be seen on the screen after pressing the cross in the right upper corner.)

![screenshot_2017-09-05-10-19-30](https://user-images.githubusercontent.com/26085443/30052367-78ed2c72-9225-11e7-8bc3-c5cbaec80a11.png)

Whatever option i choose, eduVPN will crash after 3-10 seconds (eduVPN is gestopt). After that the connection is automatically setup again and i am successfully connected

![gestopt](https://user-images.githubusercontent.com/26085443/30052366-78e7d6fa-9225-11e7-9913-846ae5df5113.png)

This is on a Samsung (S4) GT-I9505, Android 5.0.1

**Comment by dzolnai** [comment] 2017-09-05 08:52
The options not fitting the screen is an issue with translations in the library.
If you can provide me with a fitting but shorter text for those options, I could override them.
Crash should indeed not happen, will look into it.

**Comment by dzolnai** [comment] 2017-09-05 14:04
I can not reproduce the crash, tried it on multiple devices.
Can you perhaps send me the stack traces and logcat logs?

**Comment by mkoelewijn** [comment] 2017-09-07 13:36
09-07 15:32:56.117 865-1742/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:32:56.117 865-1742/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:33:03.715 865-902/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:33:03.715 865-902/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:33:03.905 865-1742/? D/ConnectivityService: getVpnConfig > session : eduVPN Demo - Secure Internet - 2001:610:450:11::1018/64, 145.90.224.90/26
09-07 15:33:04.075 865-1744/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:33:04.075 865-1744/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:33:09.140 26752-26752/? D/ResourcesManager: creating new AssetManager and set to /data/app/nl.eduvpn.app-1/base.apk
09-07 15:33:09.150 26752-26752/? W/PackageManager: Failure retrieving resources for nl.eduvpn.app: Resource ID #0x0
09-07 15:33:09.170 26752-26752/? D/StautsBar-RecentsTaskLoader: getTaskStack id: 968 label:eduVPN
09-07 15:33:09.310 26752-26752/? D/Recents_TaskViewHeader: rebindToTask task=Task (968): nl.eduvpn.app [com.android.systemui.recents.model.Task@2b19c102]
09-07 15:33:10.431 26752-26752/? D/Recents_TaskStackView: getChildViewForTask t=Task (968): nl.eduvpn.app [com.android.systemui.recents.model.Task@2b19c102]
09-07 15:33:11.472 26752-26752/? D/Recents_TaskStackView: onStackTaskRemoved Task=Task (no group): nl.eduvpn.app [com.android.systemui.recents.model.Task@2b19c102]
09-07 15:33:11.472 26752-26752/? D/Recents_TaskStackView: getChildViewForTask t=Task (no group): nl.eduvpn.app [com.android.systemui.recents.model.Task@2b19c102]
09-07 15:33:11.472 865-4671/? I/ActivityManager: Killing 23016:nl.eduvpn.app/u0a204 (adj 15): remove task
09-07 15:33:53.173 1523-1523/? I/Timeline: Timeline: Activity_launch_request id:nl.eduvpn.app time:6293166
09-07 15:33:53.183 865-2191/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:33:53.183 865-2191/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.eduvpn.app/.MainActivity (has extras)} from uid 10028 on display 0
09-07 15:33:53.203 865-1742/? I/ActivityManager: Start proc nl.eduvpn.app for activity nl.eduvpn.app/.MainActivity: pid=27390 uid=10204 gids={50204, 9997, 3003} abi=armeabi-v7a
09-07 15:33:53.283 27390-27390/? D/ResourcesManager: creating new AssetManager and set to /data/app/nl.eduvpn.app-1/base.apk
09-07 15:33:55.395 865-1742/? D/ActivityManager: bindService callerProcessName:nl.eduvpn.app, calleePkgName: nl.eduvpn.app, action: de.blinkt.openvpn.START_SERVICE
09-07 15:33:56.026 865-1021/? I/ActivityManager: Displayed nl.eduvpn.app/.MainActivity: +2s833ms
09-07 15:33:56.026 865-1021/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{bdca7b4 u0 nl.eduvpn.app/.MainActivity t974} time:6296017
09-07 15:34:07.227 27390-27390/? I/Timeline: Timeline: Activity_launch_request id:nl.eduvpn.app time:6307217
09-07 15:34:07.237 865-1296/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cmp=nl.eduvpn.app/de.blinkt.openvpn.LaunchVPN (has extras)} from uid 10204 on display 0
09-07 15:34:07.387 865-902/? D/ConnectivityService: getPackageNameFromUid: packageName value is nl.eduvpn.app
09-07 15:34:07.417 865-1742/? D/ActivityManager: startService callerProcessName:nl.eduvpn.app, calleePkgName: nl.eduvpn.app
09-07 15:34:08.608 865-2188/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:08.608 865-2188/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:08.698 865-901/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:08.698 865-901/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:08.748 865-901/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:08.748 865-901/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:09.879 865-1742/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:09.879 865-1742/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:09.969 865-1744/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:09.969 865-1744/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:10.050 865-1672/? D/ConnectivityService: getPackageNameFromUid: packageName value is nl.eduvpn.app
09-07 15:34:10.050 865-1672/? D/ConnectivityService: establishVpn called by nl.eduvpn.app
09-07 15:34:10.090 865-1672/? D/ActivityManager: bindService callerProcessName:system, calleePkgName: nl.eduvpn.app, action: android.net.VpnService
09-07 15:34:10.130 865-1672/? I/Vpn: Established by nl.eduvpn.app on tun0
09-07 15:34:10.130 865-1672/? D/ConnectivityService: establishVpn: config.session value is eduVPN Demo - Secure Internet - 2001:610:450:11::1018/64, 145.90.224.90/26
09-07 15:34:10.160 865-1298/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:10.160 865-1298/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:10.200 865-1744/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:10.200 865-1744/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:10.230 865-1296/? D/ConnectivityService: getVpnConfig > session : eduVPN Demo - Secure Internet - 2001:610:450:11::1018/64, 145.90.224.90/26
09-07 15:34:16.776 865-1620/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:16.776 865-1620/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:19.339 865-1742/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:19.339 865-1742/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:21.381 865-1744/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:21.381 865-1744/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:23.322 27390-27390/? I/Timeline: Timeline: Activity_launch_request id:nl.eduvpn.app time:6323305
09-07 15:34:23.332 865-2190/? I/ActivityManager: START u0 {cmp=nl.eduvpn.app/de.blinkt.openvpn.activities.LogWindow} from uid 10204 on display 0
09-07 15:34:23.753 865-1021/? I/ActivityManager: Displayed nl.eduvpn.app/de.blinkt.openvpn.activities.LogWindow: +404ms (total +16s511ms)
09-07 15:34:24.133 865-1021/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{285e1c1e u0 nl.eduvpn.app/de.blinkt.openvpn.activities.LogWindow t974} time:6324125
09-07 15:34:24.143 27390-27390/? V/ActivityThread: updateVisibility : ActivityRecord{3860f3f8 token=android.os.BinderProxy@2b910a0c {nl.eduvpn.app/nl.eduvpn.app.MainActivity}} show : false
09-07 15:34:26.015 27390-27390/? I/Timeline: Timeline: Activity_launch_request id:nl.eduvpn.app time:6326004
09-07 15:34:26.015 865-901/? I/ActivityManager: START u0 {cmp=nl.eduvpn.app/de.blinkt.openvpn.activities.DisconnectVPN} from uid 10204 on display 0
09-07 15:34:26.065 865-2190/? D/ActivityManager: bindService callerProcessName:nl.eduvpn.app, calleePkgName: nl.eduvpn.app, action: de.blinkt.openvpn.START_SERVICE
09-07 15:34:26.205 865-1021/? I/ActivityManager: Displayed nl.eduvpn.app/de.blinkt.openvpn.activities.DisconnectVPN: +175ms
09-07 15:34:26.375 865-1021/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1ed28764 u0 nl.eduvpn.app/de.blinkt.openvpn.activities.DisconnectVPN t974} time:6326368
09-07 15:34:26.385 27390-27390/? V/ActivityThread: updateVisibility : ActivityRecord{34f6b9ca token=android.os.BinderProxy@1b02ca81 {nl.eduvpn.app/de.blinkt.openvpn.activities.LogWindow}} show : true
09-07 15:34:28.558 865-1021/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{bdca7b4 u0 nl.eduvpn.app/.MainActivity t974} time:6328549
09-07 15:34:29.999 865-2188/? D/ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = nl.eduvpn.app,userId = 0
09-07 15:34:29.999 865-2188/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:30.079 27390-27545/? E/AndroidRuntime: FATAL EXCEPTION: OpenVPNManagementThread
                                                   Process: nl.eduvpn.app, PID: 27390
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
                                                       at de.blinkt.openvpn.fragments.LogFragment.updateByteCount(LogFragment.java:118)
                                                       at de.blinkt.openvpn.core.VpnStatus.updateByteCount(VpnStatus.java:472)
                                                       at de.blinkt.openvpn.core.OpenVpnManagementThread.processByteCount(OpenVpnManagementThread.java:417)
                                                       at de.blinkt.openvpn.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:250)
                                                       at de.blinkt.openvpn.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:215)
                                                       at de.blinkt.openvpn.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:172)
                                                       at java.lang.Thread.run(Thread.java:818)
09-07 15:34:30.089 865-4670/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname nl.eduvpn.app
09-07 15:34:30.089 865-4670/? W/ActivityManager:   Force finishing activity nl.eduvpn.app/.MainActivity
09-07 15:34:30.189 865-865/? D/CrashAnrDetector: processName: nl.eduvpn.app
09-07 15:34:30.189 865-865/? D/CrashAnrDetector: broadcastEvent : nl.eduvpn.app data_app_crash

**Comment by dzolnai** [comment] 2017-09-12 11:10
Fix submitted: https://github.com/schwabe/ics-openvpn/pull/763

**Comment by dzolnai** [comment] 2017-09-13 07:41
The fix has been merged, but I won't integrate it yet, because right now the library is on an untagged version, which can have undiscovered issues. We should wait until the next release to update.
I could patch our fork, but in my opinion, it is a kind of rare case when this can happen, so I'm leaving this as-is, so we don't have to do difficult rebases / reverts now and later.
Feel free to reopen if you disagree.

**Closed by dzolnai** 2017-09-13 07:41 UTC
